version: "3.8"
services:
  mysqldb:
    image: mysql:5.7
    restart: always
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    
    
  web:
    build: ./web
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_HOST: mysqldb
    ports:
      - "3000:3000"
    depends_on:
      - mysqldb
    stdin_open: true  
    restart: on-failure
